### PR TITLE
Adding binaries for Redmi 10C

### PR DESCRIPTION
**Pull request by Statzar**

### CODE REVIEW

**Comment by Statzar** [comment]
UFS, Buttons and Display work

**Comment by AistopGit** [comment]
Uhh, you don't have to add every single binary from your xbl. I think UFSDxe, DiskIoDxe, PartitionDxe, ButtonsDxe and ClockDxe(?) would have been enough.

**Comment by Statzar** [comment]
Huh, okay =)

**Comment by Statzar** [comment]
eta

**Review by BigfootACA — APPROVED** [review]

**Review by MollySophia — APPROVED** [review]

**Pull request merged**
